# Generated by Django 4.2 on 2024-08-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_character_contenttag_event_eventtemplate_monster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='events', to='game.character'),
        ),
        migrations.AlterField(
            model_name='event',
            name='monsters',
            field=models.ManyToManyField(blank=True, related_name='events', to='game.monster'),
        ),
    ]
