# Generated by Django 4.2 on 2024-09-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_monster_attack_alter_monster_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tick_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
