# Generated by Django 4.2 on 2024-09-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gamestate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtemplate',
            name='description',
        ),
    ]
