# Generated by Django 4.2 on 2024-09-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_eventtemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='event_function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='event_kwargs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
