# Generated by Django 4.2 on 2024-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_eventtemplate_event_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='character_changes',
            field=models.JSONField(default=list),
        ),
    ]
