# Generated by Django 4.2 on 2024-09-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_event_character_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='character_changes',
            new_name='changes',
        ),
    ]
