# Generated by Django 4.2 on 2024-09-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_rename_character_changes_event_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='changes',
            field=models.JSONField(default=dict),
        ),
    ]
