# Generated by Django 4.2 on 2024-09-12 22:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_event_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='social_effects',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship_rivalry', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('knows_about', models.JSONField(default=dict)),
                ('from_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relationships', to='game.character')),
                ('to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relationships', to='game.character')),
            ],
            options={
                'unique_together': {('from_character', 'to_character')},
            },
        ),
        migrations.AddField(
            model_name='character',
            name='relationships',
            field=models.ManyToManyField(through='game.CharacterRelationship', to='game.character'),
        ),
    ]
